 Datatype

# type()
data = 'codeswithpankaj'
print(type(data))

data = 45
print(type(data))

data = 3.4
print(type(data))

data = 56,78,67,8.9,'p4n'
print(type(data))

data = 90,
print(type(data))

data = 67.
print(type(data))

data = (45,89)
print(type(data))
data = ('codeswithpankaj',)
print(type(data))

data = [34,23,12]
print(type(data))

data = {34,23,12}
print(type(data))

data = {'name':'AASHISH'}
print(type(data))
