 Logical Operators:

# Logical AND: and
# left side | right side = result
#     T     |      T     =   T
#     T     |      F     =   F
#     F     |      T     =   F
#     F     |      F     =   F

print(45 < 90 and 67 == 90)
#        T    and    F

# Logical OR: or
# left side | right side = result
#     T     |      T     =   T
#     T     |      F     =   T
#     F     |      T     =   T
#     F     |      F     =   F

print(45 < 90 or 67 == 90)
#        T    and    F
# Logical NOT: not

print( 90 == 99)

print( not 90 == 99)
